name: DH
favicon: null
layout_spectrum: 0.50245
typography_spectrum: 0.5488191938493401
title: Dave Hacker Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5
  lightness: 0.9789137516636401
  saturation: 0.05535330809652805
  rhythmicContrast: 0.9397019143216312
purpose: []
