name: DH
favicon: null
layout_spectrum: 0.80218
typography_spectrum: 0.64416
title: Dave Hacker Photography
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a0a0a0'
    - '#616161'
    - '#cacaca'
    - '#0e0e0e'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
