name: DH
favicon: null
layout_spectrum: 0.73927
typography_spectrum: 0.64416
title: Dave Hacker Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a0a0a0'
    - '#616161'
    - '#cacaca'
    - '#0e0e0e'
  brandStrength: 1
  lightness: 0
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
